AllSoldOut/Controllers/StoreController.cs
using AllSoldOut.Models;
using AllSoldOut.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace AllSoldOut.Controllers
{
    public class StoreController : Controller
    {
        private readonly ILogger<StoreController> _logger;
        private  ApplicationDbContext _context;
        private IHostingEnvironment _env;

        public StoreController(ApplicationDbContext context, ILogger<StoreController> logger, IHostingEnvironment env)
        {
            _context = context;
            _logger = logger;
            _env = env;

        }

        //Returns a list of available products in the products
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetInt32("role") != 1)
            {
                return RedirectToAction("Index", "Login");
            }
            var products = await _context.products.Where(x => x.available == true).OrderByDescending(x =>x.dateCreated) .ToListAsync();

            return View("index", products);
        }

        //Returns the Create project page 
        [HttpGet]
        public IActionResult Create()
        {
            if (HttpContext.Session.GetInt32("role") != 1)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        //Create the product and calls a method "SaveImage" that saves the upploaded image in the www root folder 
        [HttpPost]
        public async Task<IActionResult> OnCreate (Product products, Specifications specifications, IFormFile productImage)
        {
            if (HttpContext.Session.GetInt32("role") != 1)
            {
                return RedirectToAction("Index", "Login");
            }
            products.quantityAvailable = products.inStock;
            
            await _context.products.AddAsync(products);
            //Adding Date 
            products.dateCreated = DateTime.Now;

            //Saving the filename to db & the file to folder
            if (productImage != null)
            {
                string fileName = products.productName + "_" + RandomString(4);
                this.SaveImage(productImage, fileName);
                products.productImageName = fileName;
            }

            await _context.specifications.AddAsync(specifications);
            await _context.SaveChangesAsync();


            return RedirectToAction("Index");
        }

        //Get RandomString for the File Name
        public string RandomString(int length)
        {
            const string valid = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
            StringBuilder res = new StringBuilder();
            using (RNGCryptoServiceProvider rng = new RNGCryptoServiceProvider())
            {
                byte[] uBuffer = new byte[sizeof(uint)];

                while (length-- > 0)
                {
                    rng.GetBytes(uBuffer);
                    uint num = BitConverter.ToUInt32(uBuffer, 0);
                    res.Append(valid[(int)(num % (uint)valid.Length)]);
                }
            }

            return res.ToString();
        }

        //Save Image
        public void SaveImage(IFormFile formFile, string fileName)
        {
            string wwwPath = this._env.WebRootPath;
            string path = Path.Combine(wwwPath, "Files");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            string picName = Path.GetFileName(fileName+".png");
            using (FileStream stream = new FileStream(Path.Combine(path, picName), FileMode.Create))
            {
                formFile.CopyTo(stream);
                //ViewBag.Message += string.Format("<b>{0}</b> uploaded.<br />", fileName);
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            if (HttpContext.Session.GetInt32("role") != 1)
            {
                return RedirectToAction("Index", "Login");
            }
            try
            {
                var product = await _context.products.Where(x => x.productId == id).FirstOrDefaultAsync();
                var spec = await _context.specifications.Where(x => x.productId == id).FirstOrDefaultAsync();

                PhoneDetailsViewModel phone = new PhoneDetailsViewModel()
                {
                    products = product,
                    specifications = spec,
                };
                ViewBag.path = Url.Content("~/Files/"+(phone.products.productImageName).ToString()+".png");
                return View("Details", phone);
                //return Json(phone);
            }
            catch (Exception e)
            {

                throw;
            }
            
        }

        [HttpGet]
        //public IActionResult SalesDetails(int id)
        //{
        //    var data = from products in _context.Set<Phone>()
        //               join sales in _context.Set<Sales>()
        //               on products.salesId equals sales.salesId
        //               select new { products, sales };
        //    return View("Details", data);
        //}

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (HttpContext.Session.GetInt32("role") != 1)
            {
                return RedirectToAction("Index", "Login");
            }
            var product = await _context.products.Where(x => x.productId == id).FirstOrDefaultAsync();
            var spec = await _context.specifications.Where(x => x.productId == id).FirstOrDefaultAsync();

            var phoneCategory = await _context.phoneMakers.Select(x => new { x.makerName }).AnyAsync();

            PhoneCreateViewModel phone = new PhoneCreateViewModel()
            {
                products = product,
                specifications = spec,
                //phoneMakers = phoneCategory,
            };
            ViewBag.path = Url.Content("~/Files/" + (phone.products.productImageName).ToString() + ".png");
            ViewBag.fileName = (phone.products.productImageName).ToString() + ".png";

            //Getting the Phone Categories.
            
            return View("Edit", phone);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Product products, Specifications specifications, IFormFile productImage)
        {
            if (HttpContext.Session.GetInt32("role") != 1)
            {
                return RedirectToAction("Index", "Login");
            }
            if (ModelState.IsValid)
            {
                var data = await _context.products.Where(x => x.productId == products.productId).FirstOrDefaultAsync(); 
                data.productName = products.productName;
                data.productCategory = products.productCategory;
                data.productDescription = products.productDescription;
                data.productPrice = products.productPrice;
                data.productColor = products.productColor;

                products.dateCreated = DateTime.Now;

                //Saving the filename to db & the file to folder
                if (productImage != null)
                {
                    string fileName = products.productName + "_" + RandomString(4);
                    this.SaveImage(productImage, fileName);
                    data.productImageName = fileName;
                }


                //Updating the Specifications
                var spec = await _context.specifications.Where(x => x.productId == products.productId).FirstOrDefaultAsync();
                spec.launchDate = specifications.launchDate;
                spec.bodyDimension = specifications.bodyDimension;
                spec.bodyWeight = specifications.bodyWeight;
                spec.displayResolution = specifications.displayResolution;
                spec.displaySize = specifications.displaySize;
                spec.platformOS = specifications.platformOS;
                spec.ram = specifications.ram;
                spec.internalMemory = specifications.internalMemory;
                spec.camera = specifications.camera;
                spec.batteryStandbyTime = specifications.batteryStandbyTime;


                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Details", new { id = products.productId });

        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (HttpContext.Session.GetInt32("role") != 1)
            {
                return RedirectToAction("Index", "Login");
            }
            var phone = await _context.products.Where(x => x.productId == id).FirstOrDefaultAsync();
             _context.products.Remove(phone);

            var spec = await _context.specifications.Where(x => x.productId == id).FirstOrDefaultAsync();
            _context.specifications.Remove(spec);

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

AllSoldOut/ViewComponents/CartItemViewComponent.cs
using AllSoldOut.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AllSoldOut.ViewComponents
{
    public class CartItemViewComponent : ViewComponent
    {
        private readonly CartContext _context;

        public CartItemViewComponent(CartContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cartItems = await GetItemsAsync();
            ViewBag.sumOfTotal = await _context.carts.Select(y => y.total).SumAsync();

            return View(cartItems);
        }
        private Task<List<Cart>> GetItemsAsync()
        {
            return _context.carts.ToListAsync();
        }
    }
}

AllSoldOut/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AllSoldOut</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <script language="JavaScript" src="https://code.jquery.com/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script language="JavaScript" src="https://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script language="JavaScript" src="https://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.css">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/table.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-info" asp-controller="Store" asp-action="Index"><b>Store</b></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Home" asp-action="Index">Customer View</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AllSoldOut - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#dtBasicExample').DataTable({
                "pagingType": "simple"
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AllSoldOut/Views/Shared/_Layout.cshtml
@{
    @using Microsoft.AspNetCore.Http;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>AllSoldOut - 2 Seconds, Everything Sold Out</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="~/css/theme/bootstrap.min.css" />

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href="~/css/theme/slick.css" />
    <link type="text/css" rel="stylesheet" href="~/css/theme/slick-theme.css" />

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href="~/css/theme/nouislider.min.css" />

    <!-- Font Awesome Icon -->
    <link type="text/css" rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="~/css/theme/style.css" />
    <script src="~/js/theme/jquery.min.js"></script>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <!-- HEADER -->
    <header>
        <!-- TOP HEADER -->
        <div id="top-header">
            <div class="container">
                <ul class="header-links pull-left">
                    <li><a href="#"><i class="fa fa-phone"></i> +234-903-458-2835</a></li>
                    <li><a href="#"><i class="fa fa-envelope-o"></i> allsoldout@yahoo.com</a></li>
                    <li><a href="#"><i class="fa fa-map-marker"></i> 714 Adetokunbo Ademola, Victoria Island</a></li>
                </ul>
                <ul class="header-links pull-right">
                    <li><a href="#"><i class="fa fa-dollar"></i> USD</a></li>
                    <li><a href="#"><i class="fa fa-user-o"></i> My Account</a></li>
                </ul>
            </div>
        </div>
        <!-- /TOP HEADER -->
        <!-- MAIN HEADER -->
        <div id="header">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <!-- LOGO -->
                    @*<div class="col-md-3">
                        <div class="header-logo">
                            <a href="#" class="logo">
                                <img src="~/img/logo.png" alt="" height="100" width="100">

                            </a>
                        </div>
                    </div>*@
                    <!-- /LOGO -->
                    <!-- SEARCH BAR -->
                    <div class="col-md-9">
                        <div class="header-search">
                            <form>
                                <select class="input-select">
                                    <option value="0">All Categories</option>
                                    <option value="Iphone">Iphone</option>
                                    <option value="Samsung">Samsung</option>
                                    <option value="Tecno">Tecno</option>
                                    <option value="Infinix">Infinix</option>
                                    <option value="Nokia">Nokia</option>
                                    <option value="lg">LG</option>
                                </select>
                                <input class="input" placeholder="Search here">
                                <button class="search-btn">Search</button>
                            </form>
                        </div>
                    </div>
                    <!-- /SEARCH BAR -->
                    <!-- ACCOUNT -->
                    <div class="col-md-3 clearfix">
                        <div class="header-ctn">
                            <!-- Cart -->

                            <div class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true" asp-action="">
                                    <i class="fa fa-shopping-cart"></i>
                                    <span>Your Cart</span>
                                    <div class="qty">@ViewBag.countCart</div>
                                </a>

                                <div class="cart-dropdown">
                                    @await Component.InvokeAsync("CartItem")
                                </div>


                                <!---DROPDOWN HERE-->
                            </div>
                            <!-- /Cart -->
                            <!-- Menu Toogle -->
                            <div class="menu-toggle">
                                <a href="#">
                                    <i class="fa fa-bars"></i>
                                    <span>Menu</span>
                                </a>
                            </div>
                            <!-- /Menu Toogle -->
                        </div>
                    </div>
                    <!-- /ACCOUNT -->
                </div>
                <!-- row -->
            </div>
            <!-- container -->
        </div>
        <!-- /MAIN HEADER -->
    </header>
    <!-- /HEADER -->
    <!-- NAVIGATION -->
    <nav id="navigation">
        <!-- container -->
        <div class="container">
            <!-- responsive-nav -->
            <div id="responsive-nav">
                <!-- NAV -->
                <ul class="main-nav nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                </ul>
                <!-- /NAV -->
            </div>
            <!-- /responsive-nav -->
        </div>
        <!-- /container -->
    </nav>
    <!-- /NAVIGATION -->


    @RenderBody()

    <div id="newsletter" class="section"></div>
    <footer id="footer">
        <!-- top footer -->
        <div class="section">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">About Us</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
                            <ul class="footer-links">
                                <li><a href="#"><i class="fa fa-map-marker"></i>714 Adetokunbo Ademola, Victoria Island</a></li>
                                <li><a href="#"><i class="fa fa-phone"></i>+234-903-458-2835</a></li>
                                <li><a href="#"><i class="fa fa-envelope-o"></i>allsoldout@yahoo.com</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Categories</h3>
                            <ul class="footer-links">
                                <li><a href="#">Iphones</a></li>
                                <li><a href="#">Androids</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="clearfix visible-xs"></div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Information</h3>
                            <ul class="footer-links">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Contact Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Orders and Returns</a></li>
                                <li><a href="#">Terms & Conditions</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Service</h3>
                            <ul class="footer-links">
                                <li><a href="#">My Account</a></li>
                                <li><a href="#">View Cart</a></li>
                                <li><a href="#">Wishlist</a></li>
                                <li><a href="#">Track My Order</a></li>
                                <li><a href="#">Help</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /top footer -->
        <!-- bottom footer -->
        <div id="bottom-footer" class="section">
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-12 text-center">
                        <ul class="footer-payments">
                            <li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
                            <li><a href="#"><i class="fa fa-credit-card"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
                        </ul>
                        <span class="copyright">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This Simple E-Commerce Application is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://github.com/herbayomi4" target="_blank">Oluwaseun Adeyemi</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </span>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /bottom footer -->
    </footer>
    <!-- /FOOTER -->
    <!-- jQuery Plugins -->
    <script src="~/js/theme/bootstrap.min.js"></script>
    <script src="~/js/theme/slick.min.js"></script>
    <script src="~/js/theme/nouislider.min.js"></script>
    <script src="~/js/theme/jquery.zoom.min.js"></script>
    <script src="~/js/theme/main.js"></script>

</body>
</html>